matrix:
- name: Markdown
  aspell:
    lang: pt
  dictionary:
    wordlists:
    - .wordlist-pt-br.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'release-pt-br/**/*.md'
  default_encoding: utf-8
